spring:
  profiles:
    active: develop-mysql
    group:
      develop-h2:
        - common
        - develop
      develop-mysql:
        - common
        - develop
---
spring:
  config:
    activate:
      on-profile: common
naver:
  developers:
    client:
      id: ${NAVER_DEVELOPERS_CLIENT_ID:}
      secret: ${NAVER_DEVELOPERS_CLIENT_SECRET:}
---
spring:
  config:
    activate:
      on-profile: develop
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        DEBUG
---
spring:
  config:
    activate:
      on-profile: develop-mysql
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:/db/migration/mysql
---
spring:
  config:
    activate:
      on-profile: develop-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
  flyway:
    locations: classpath:/db/migration/h2