spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
  flyway:
    locations: classpath:/db/migration/h2