spring:
  profiles:
    active: develop-mysql
---
spring:
  config:
    activate:
      on-profile: develop-mysql
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    locations: classpath:/db/migration/mysql
---
spring:

  config:
    activate:
      on-profile: develop-h2
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;
  flyway:
    locations: classpath:/db/migration/h2