INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Behind Enemy Lines Collection','/baDDWPQgZyBKiDNeipLJ9LEZ5BX.jpg','/5sMWk8wutGCFAM7MAFPQJyc0ny0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('See No Evil Collection','/i8oH7qZXgg96r03Tyf8BEe2x52M.jpg','/xUwlkY068q0VJrBpcyShwNwVoRI.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Brother Bear Collection','/pl2qWUqiYBSGErVm8an8BIkZaai.jpg','/3BzGz46K4DIH7Ut7KRe0u9bI1Gm.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('A Nightmare on Elm Street Collection','/BcgmrOz69AUBRukw5LLGeYsOgo.jpg','/7UcPLgNneoemYmZcyUo5r3nwBbE.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mannequin Collection','/tHUiRPu9PmsgDEa4j22fjWHjFkW.jpg','/qNRyB22N3Y6aGii099by5I51KDJ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Beauty and the Beast Collection','/mIzZxNAT1GIFaEoPYdJsUKC23Oj.jpg','/xy1rMVQnDixSe91IF31Pxdqt3Gk.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Honey Collection','/jnMYWzVz4Tflsog6Ik6Mop17LSV.jpg','/nldi0pe9vJyUg87nE6OjL5MzrDn.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('National Lampoon''s Van Wilder Collection','/9O9Dtdetrc7shP2CUr5jQqbIexC.jpg','/afX0zjd1fFYNXrndzD9jd7gHvi3.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Seven Dwarfs Collection','/AnGl2TN7GBR0u49wTbNPTk1ShrB.jpg','/xtR1Y5pgriouge533T6qDoyRfWK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Hunt for Eagle One Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Miss Congeniality Collection','/wgQWsSsvB1iu1Pwc4nUP9E5bRzs.jpg','/7TIT28YbhAOeQGD2q2hJ9j83jI1.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lucky Stars Collection','/wHlyDQyfBEeEqSxtAls7xokl0lj.jpg','/c1Yf8AtAAobnWlrlrE6KpGhOIl4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('District 13 Collection','/f8duPjfo6wzbd7xLKwhbQYv986B.jpg','/6d8jbKsWVUKrKBHMcf9mvBkFCgv.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('When a Stranger Calls Collection','/7UbKcurnuSzVrMbHsISa5AfLNNp.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Spy Kids Collection','/yqpS8N5w7VYo3gmFtHsGwHTV4Td.jpg','/oxjNAfQJ1OrySttZSeLayky6T9k.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Escape From ... Collection','/fCHWtXyAueRG7RXk2pyRhN7t7hu.jpg','/c9mWaF2oeodriDLqYQr425sasxo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Amityville Collection','/stPXPasI1lvxJRJJuDCKBr6X836.jpg','/oLwHD09Eb46PecSckniikt7aBhw.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('9½ Weeks Collection','/w43wrBCvWS0gTremaIaFqaMoKWm.jpg','/lwajd7A0z7WQ132S0sot6YjFzBU.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Feast Collection','/1clQ6DCLxmvysHkU7HxWToDzuPo.jpg','/qtD9j2sHcyVHUbbT6To5AHAlLir.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Evil Bong Collection','/fzaI7Bkqeg5gm9iEZT02GUCcm6R.jpg','/wfow115NhNwWsLzyq0H5n1jNQEP.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dorm Daze Collection','/zw4H0deFWWoktReTmiRSdLYj3F9.jpg','/pkRyV44Zyn6KOySQQT9DHbAhT8D.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Saints and Soldiers Collection','/ypL9pYL6dY7zO12r4qYIQM1Ekvr.jpg','/uAv2zvBtIGujt9jGELeHKEaNjRi.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Critters Collection','/rWZytVHeFsADHeuoPCIf4c7Qepb.jpg','/9K0ycQWRv4vSL1oM8y7dOXwFpy6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Alien Nation Collection','/sXdKjBbdBimtARvWdVFEsxc4kxu.jpg','/s8TyKSfmSlvaLKTqJLpkCCIiLK8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cyborg Collection','/fxf2Md5RGMMxgM9yNyr0h1Wvaxu.jpg','/5EGXww0h3TJ3xaHJ0sNEmbRPn35.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Road House Collection','/cadfcktKwvKMpg9FFvCTTzj9pFY.jpg','/3sC0DdygqYHesLqzFT8etDmDTAX.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Stuart Little Collection','/tBWjHQBmEa91Pa3R96zGdosULom.jpg','/diOx2L0SIlgrriuYebChp9UNX65.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Iron Man Collection','/fbeJ7f0aD4A112Bc1tnpzyn82xO.jpg','/rI8zOWkRQJdlAyQ6WJOSlYK6JxZ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Chronicles of Narnia Collection','/sh6Kn8VBfXotJ6qsvJkdfscxXKR.jpg','/vlv2skpXYg02TRg1iyXGvDvZSZ9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Little Mermaid Collection','/y0EOuK02TasfRGSZBdv5U910QaV.jpg','/qNNOYLWLlEQARRT0z37DSrWx3NV.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Bad Santa Collection','/2OkB4GagVy1n7M8Q94FRzsOErPE.jpg','/5hmQCwMOoZWzCgI08Yx7lNdxhqH.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Brooklyn Cigar Store Collection','/bgiPsYjbjbRFmEeUfYlp8ZDBVJJ.jpg','/r4Ov7P8OADcOxfpuDujoJl2Cqry.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dumb and Dumber Collection','/e00cVFjUaiKEiTY1rWlSxACN3fz.jpg','/saUnj5K6buVafDfLfTozDH2eqdC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Police Academy Collection','/q6npkfLX1jryO4a3GI63WJW9TrT.jpg','/4fjmNFs31JPfa4rYtE3gNDspGlk.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Lawnmower Man Collection','/h4LvlswVUclYt1kFLN0PVFV3NXC.jpg','/3hPpPp7cwMiwJ1TFf0hANcw7AnG.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Half Past Dead Collection','/ax2pkKGepYqrEj3JmN5LDVmjZyI.jpg','/lJbaf1KOwlRpMkRf6ABDU3nN7Jo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Are We Collection','/fyQ1tpTvag7IXBJOhltUomI4LUv.jpg','/uZRixx529cMcwqmYW5xGFIso7Q3.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Sisterhood of the Traveling Pants Collection','/x9akgmvnUHYi8PXAFyBbdJIjrvf.jpg','/u0kYMfyYCEKuWvf3zZLorEhUKzR.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('How to Train Your Dragon Collection','/hS8y3BcPki0GQKRQeGQVAz6BijK.jpg','/mvcfPkOvgDJG2lEAxTz0NKqoQLo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Shrek Collection','/qNHZMe92A7Pyl46qUH29hVOtbSK.jpg','/gMWrKQjoTIpYjhc8SxZF20EDIES.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Toy Story Collection','/bDSe7UCiShmiTz7kuOjMyP6mz7l.jpg','/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Thor Collection','/yw7gr7DhHHVTLlO8Se8uH17TDMA.jpg','/3KL8UNKFWgIKXzLHjwY0uwgjzYl.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Muppet Collection','/3O2tEgn8Z5atIVKif6W47qayIqb.jpg','/1AWd3MM90G47mxtD112gRDxSXY9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('From Dusk Till Dawn Collection','/a156nAy5ZTGXlO5wgfvnF26aaDB.jpg','/g1KtXRjYRoUQ6v0r6eMe4qbs7ll.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Mask Collection','/pl2vNt9XlxITTgm8wCQ2Y6ThkpT.jpg','/ucDNm5TJW1ji7kIjnX2SZYm7ATM.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Species Collection','/t5J0JH1L8L7CmtC3sL3K2ybgTbE.jpg','/vnpcoCTZhg1EdEog1kAS0pklx1o.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Kickboxer Collection','/frOnbHEHWISXBC43wjsrBGOhqGJ.jpg','/lnUDOYV8hUOrXAx1RFpJeguenuQ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Friday the 13th Collection','/zIsnaiX2ox5hy6oJrmyZv5SojNG.jpg','/yz9EdlfKU8bpN0hbdJMy6QkFBoN.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Monsieur Hulot - Saga','/9CrEgVnkIm0SMbuFgBPhEi9P9I4.jpg','/zGjOWVzgEZiHHM6L1pp5eAgBqio.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Pokémon Collection','/oUdOt0VbJQnkLwOiQLPJLxH8oCA.jpg','/xQM02GXLgC0HxMHOCUIxTsjzi1O.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Porky''s Collection','/fGnfEA244AKrKgcN6uyvEFCgaR6.jpg','/1Ra6Un73JwIjGHfEU0lM3397Q8z.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Animal Collection','/pVTqahiP9FdaaEPVTB97FDA61SQ.jpg','/beYWLGf2QzOCYdlSqrJIy5i1on0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Twins Effect Collection','/o6NAml8DpguaI20s8ITE1Oubahd.jpg','/9TZdfribk0oEQbJoZ0dznnx4HcX.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('My New Partner Collection','/pL7LFFp663cLni9Ukjq5BxPB9Js.jpg','/xlWqvs10lNrIrXvMl8Cakv30H3e.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Raiders Collection','/e7iu318u2PF96V2ynOLyTqaQvWH.jpg','/bZxVifVhDmrjp0kDHrvvuFkSA6k.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Shaolin Temple Collection','/jwG2CwxBrN4aVpyTrSIDhiy6sD6.jpg','/grC83MtaWyTbUcxndTK3khIWiMT.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Urban Legend Collection','/oa0QIdVg3BLZHU6fm9kAF2lXCVq.jpg','/1MllG91Hzn5cgmN4uFn0Jg2D0i6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Vacancy Collection','/wDLo8s0HEd1ci5980gpk3GoD2DL.jpg','/AmzchMREhCLicBZNpUaCXc6f5jQ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Romancing the Stone Collection','/ecjnbQWgcFA8YEbJlVC0IZFLuGs.jpg','/duC10LBJE51nzOSNm7ZbWppMxTC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Starship Troopers Collection','/uumu3Xj1ME1632SCsyVJwITgOKZ.jpg','/hwZXCuY6GVw50o17nDGbSR8WMFJ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Poltergeist Collection','/8Z6P04pKGvCnkmHdAl2lmbfAIbN.jpg','/i8QZZV1olny9FCPNrxAL7Kk9CJy.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Ring Collection','/500xj7l72BojMZ3tNBJY46tg5YJ.jpg','/jXlFymc442CEMB5h3d62GeJefnW.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Clash of the Titans Collection','/3TXIuCHr2m9oZcLJOc5qo9o5WsT.jpg','/vmE52XvE2yWWQFt4g1x17K070gY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Legally Blonde Collection','/2hRPa13K9cljmKJdaLVs1J1zzay.jpg','/aabPyPAA6E8hJ7tUipwunr3Itzb.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cocoon Collection','/eK2cdRZ5KsR1m6yyrQWbtxPE8zh.jpg','/o32F4wuQJPBnP5FVkOGP9DxGYJI.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Living Dead Collection','/5tzYvD8a7M6YdGy37V5goRJXsMk.jpg','/inPPfnJ9Wzc9rg1MpkPm0P3D9rJ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lady and the Tramp Collection','/fvk72hTShONXVDDSdoTEVm7DJh0.jpg','/8YIec6FKfOHn9uw7MMH1200wbyK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Fly (1986) Collection','/r6mRcDV2MIbDQ79JpeGls5DnDfr.jpg','/6nU5cC8qaVO3hzSMDMJp4HCFwDA.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('K-9 Collection','/moEkdT6SE1HxR9QHwor6DJX8NYe.jpg','/mdG3H2w9Ktc2Ua6tJie3eUE8Zte.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Wishmaster Collection','/1FDfl0PEnapO6c1BSgMrFgkM9f3.jpg','/yCTkIUEOwc7HAGAoZGK85MK8dAd.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Visitors Collection','/tqLSEkKYdkFCqsNHP1v9pnr0sl.jpg','/ywYnkeaa7LZBU1bW8zavPwzve4X.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Ginger Snaps Collection','/nqt1FUoBERJ98CbNM8NClg5Kknc.jpg','/gPzW1WAb9Pi1vj9JMxzi3DIhhO9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Universal Soldier Collection','/w6VKg5MJFmoACGgLcDUMmNSPYOv.jpg','/bonZuSo9YE7LFHEFE8oLD3qv32o.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Wild Things Collection','/4OI3VZMXFMcTmpyzg9RlN4vsIro.jpg','/uE47SwTt7uHyVwpMzcCQ92Q7FsQ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Star Wars: The Ewok Adventures Collection','/jxZLPyzVniOkXiCWWjehxXT08Zl.jpg','/VXwSW7UGuNScCTy5V5H9pgioir.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('An American Tail Collection','/spEFy5eHaNuINNHhwtCWKy1bBiY.jpg','/eBwQDs5JbnL3mJhKY7HBeiY9xwe.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Eye Collection','/mEHiHHIWG0I7lL5RwgGSn8ZAfKn.jpg','/rki7UPSFEaUPuitlQ9Iq421p137.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Deuce Bigalow Collection','/2i85QqJeASgR6Zbg24YMFzllvNi.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Flodder Collection','/zLQ3Yc32F6BXAsffHqUFDHWokoe.jpg','/ratYEDKH8Ev8xe597rPxmwe1omh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Mighty Ducks Collection','/3Fhf0oteJHXmCNUEVZjyx8AzldY.jpg','/qBFCtw5EKBj3ILFbRgXtCfCjmb8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Friday Collection','/cJUiqO2Z0PDL6cZ2Ic04F1i4gnb.jpg','/pXszT8ZWGj3fohU9FY0niA0IDEw.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Damiel and Cassiel',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Beethoven Collection','/pdaH4A7ecsThnSX5sOpwrcntziF.jpg','/9E3qVeuprE4iVDQyFDNPlo03a4D.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dr. Mabuse Collection','/e9iMj6Xb1MSTqK7ypCa6fGQyLn2.jpg','/zRQ1anFPQVP0WrnvgV7uKFEsX9i.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Simon Brenner Collection','/gd1AXBaLsl3F0zBQh9XcBl8kr2E.jpg','/aS4ZAsxx4wa4N1gWpuBUgmKE0S5.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Werner Collection','/aYzh0f21peIjtQqZsb7ufH0MqLh.jpg','/ukLAZl7cZNjCFNN1myDy3a7jYTA.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('DragonHeart Collection','/bZsqwJnO65wlZ3ez7dopUQMYALY.jpg','/hRucBWgzCc7iA9avUE2k5gc7dkj.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('101 Dalmatians (Live-Action) Collection','/oSeIai1ioj4dbq7WgbPzpsSCzkS.jpg','/eTaNHqpi7VldgcrDetfTzk4FeDi.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Death Race Collection','/uffHLg0ekFlErCp7OkpecXkWPng.jpg','/cGaVuq8ZjX1UPD9wPRlzx6lP9kK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Nim''s Island Collection','/rRPq295zZflnjp9Y8uhJppJBayQ.jpg','/iRh0E4dR2m7ZiJQ9u58r8jPV0WU.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Karate Kid Collection','/o6h2F0C5eZOy50Q76fNYzc9mvvw.jpg','/1ok5JGCsDt4Sh3CkFeXh2F2KB7F.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Bats Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('スタジオジブリ Sutajio Jiburi','/28mNNxFtnuN2UlaAljAx6qjz8zW.jpg','/a4b7VYvZjEZ0OqWAeFHMui9kcnK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Troops Collection','/lvn6Bi65GcOPVbTJlgvZDEiTFIk.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Madagascar Collection','/99VF9o8Zuq4mh5px4bBaZvcKyQS.jpg','/lzTIAbvMeGWB7PUrmBZXulGA28M.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Sherlock Holmes Collection','/bsUN9Ph1nUituteKWOhPQGguNXt.jpg','/kT4Pz6QY29qHMVKULzNrVHg6Vwg.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Pocahontas Collection','/fcFFdNwgkLXCdIxe0H7RFasmogh.jpg','/qqeOxNmtAW7WXdbrmQftgluvve7.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Hunchback of Notre Dame Collection','/vX0k6lP6tBi8XHdvNtOvsbNgyxM.jpg','/rlKlVPPsQ5RpiEpm0tZsrQPgyLc.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Crow Collection','/kfU8OZptlBfR5DL9LNGL301Zmlz.jpg','/xxJs7xqY0vMuNlznQboBzq8RlZm.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Arrival Collection','/hcURy1riW3qLFHQdf9b7bGy8NkQ.jpg','/rEk9ZLfrYXL87CMEddMaYAOwC39.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('East is East Collection','/aCRRl0LNpFgkwyW66OlcdfwVUs3.jpg','/tx3cY0yY2xWIT1shMOTOLJH8Nx4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Center Stage Collection','/uQDnd1Ws2w62WTDsjOxLyOYoWqL.jpg','/iNDAKlYSc1TGB0EutAzw7OObGrt.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Heaven, Hell and Purgatory Collection','/uckGIB5UU6xQ9aQtVpNDgNgBmPJ.jpg','/10M9tkfCV65efgNVo5SWHW2Kipi.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Psycho Collection','/29pDqAgmb4idzWzuZncoT7LZplA.jpg','/qawcCCyJNcdOpDRuXo5aJJycecY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dracula 2000 Collection','/4EGw7TK4rgts1pLI9E3U6681nWN.jpg','/aD4nL9HsMDU8sCEAe7wdeHMiSr2.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lemon Popsicle Collection','/kip5iBH8jb4nXb8ec8M7YyxoLxt.jpg','/trmtEmNjlh2OxRjkJFG02TaFFYO.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Child''s Play Collection','/fLWDbZziq47lcN28Q1ILnIMLHEC.jpg','/AAhYXBVIEl6WgQnzfBsauTIC25.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Skulls Collection','/yC65pXcgtnsF6chNwqQe0QhiyY.jpg','/mTPVUQJ87z7FzJvtmCjXixJb8iD.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Die Musterknaben Collection','/nUkchC4U6fSJMvDCC6oITXtkhEP.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('George of the Jungle Collection','/4zBbsGW3QXmZcNyKNAvth9gYW9e.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Vampires Collection','/p15toVzxdYPN90V6vuHZAEhTVCj.jpg','/gbzoe6GXgEP9c0RkSIPy0Oh6EIs.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Philadelphia Experiment Collection','/5Ai1fCh89GC9a45OzdgfRs3lg67.jpg','/xudPnQgz1n3ZNFu9Co82s3qFoB2.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Barbershop Collection','/glSSzT4jwKblxxGXN0lHWxbyhUH.jpg','/lCvX9g4vvxFUgJGNlFwfkZJWGiB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Once Upon a Time in China Collection','/zYDFE84tanonIGZj7DNqSHe9Zfj.jpg','/gQNRJ3ChYVkqGtAOgmWJKr3uw1x.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mean Girls Collection','/bg3Z9SAlOWJFEK1c9QGMt3Gw8g0.jpg','/qCyRzC5EibFNCL8gzLVqgSvYvsB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Kangaroo Jack','/vpYZkVpkr3zhov7GnNMpHPVoXoq.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Virgil Tibbs Collection','/cSKqpR4LJHq4Wypji1JbzuBj4us.jpg','/tILvRk8Q50IzgZRC9PBccIKFoHN.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Winnetou Collection','/63hexCX9ssm2DvaxknsMMou0t7A.jpg','/xv9eWhlX6QVR6HbuInToXYdf8qO.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Westworld Collection','/cezpGxSMDsWjwrS7VwMqZ5N4Ay8.jpg','/3yzaSCXO8cT7Q1tgCsmf8ypSxRI.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Godzilla (Millennium) Collection','/1B3UASu6XDE1R9wzE3K9QIipnBj.jpg','/hhUQwi9Z7wE2kwwC1AM1AE418oU.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Das Sams Collection','/rXQVJyIgp0snzEV3wLIDtp0PJGp.jpg','/c4VIScNY0nXx7CLrikWYR9AvrF2.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dirty Harry Collection','/adfj0Cf1TwHBQgXkxJzOxlmxhhe.jpg','/nlpixhOhb3JmFqVXKjCwpYFpldf.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('American Civil War Collection','/vsKgRqTYvMykunDnP5rsVkHVnYs.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('[REC] Collection','/jTA37dMZVUFej20EoM5SomKtnYi.jpg','/rDzuccVBZSyNVQ26hTRT0DvneVA.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Strangers Collection','/yDnz0tE4QEQ8NjcZpgJ6g3PCdp5.jpg','/6m71j6oywKtXgwO0oxm28YwKOiu.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Airport Collection','/yDnEIOmCgPZJ55d8WeRjlgqgi78.jpg','/6mU9FtwksOjoEQylN2J0EFTTFc6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Wall Street Collection','/6eT4277jNMQ8qTODYjxoNbYJhgZ.jpg','/sEKYBSwZFFppJ5GmEVxsECr7ilR.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mulan Collection','/1fjZKATXsAKvtO6uJqCiNL5u4mK.jpg','/uzQqTJMTCcAbXCg3LUsiA8cJ5m0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Halloween Collection','/2uqHV6YcD9jEL2WuJYjXiiuRDqd.jpg','/d6uWYZe7h7M3F7h4IBjO1jgIkMh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dirty Dancing Collection','/gkrOvdbCFuGlxVwCYmczw7aw6Ku.jpg','/qR6POAKwCL8VwuK8ZjSAdRRFNj9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Iron Sky Collection','/kjuDiz5vGEBVqPYZpl4Tzue2v6S.jpg','/A3gUwCnqz05B6wtZrunWrbcT9jt.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Henry: Portrait of a Serial Killer Collection','/6QTtWHXfyRO9HYnpKk6tCuIut0p.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Peter Pan Collection','/t0mINaIut2aDKdGseQtC7UcbRNW.jpg','/zh0cQo2etEeePAQZkCMta7vvlBm.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mimic Collection','/wu9bW6MiaT5LFIEwyplr1D9wnAk.jpg','/oOZpLQaVyoWDgQ41lGlToRlH1aB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Daddy Day Camp Collection','/xhD1mbjJmhSNejP59fh8o7EYcv7.jpg','/hQXX7E22e1xJVudoNgZJn95BIAl.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('French Connection Collection','/z47XPRqvTpgw4QarhFkF0fDarDg.jpg','/islbdTICsxPE1c3YEFzEc9Wb46p.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('American Psycho Collection','/ko4O9lcRGYOZAF5Hh79Mfsgjpun.jpg','/5nrkaUQe4m3FLYJrFPGnkMGeQXD.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('King Kong (Remake) Collection','/uf59XiQnBOEo6l7kV2O3WvPciAs.jpg','/k98iowBJdKDRKbllrpdpk4SarJE.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Theo Gromberg Filmreihe','/hfeKItX6OGi6fKFMM3ImsG7jThq.jpg','/jrgfvvoTiBDlIY5ToVqzowf8JqY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Josey Wales Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('St. Trinian''s Collection','/siu1m6v3zhW0DM6w5qBvvc14eCf.jpg','/8ZB31bmNPtldnpm5anQlFHAnCe0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('In China They Eat Dogs Collection','/ws7sHs7oVSoVgrLTlEitJ2mJGR8.jpg','/jeH6MaDD1CnZ8TLupBAi0DYWn2F.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Police Story Collection','/zF4gP4w1xxM7jDKLjTDK3ixkkms.jpg','/5qbfJzkMAUkFxcVo0dqnTRmpUoh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Wild Soccer Bunch Collection','/mbvXqW1Y2ewRcA3EBUtj26EDGlz.jpg','/pVPrPTADDdOGT2AqOw8320sU2dU.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Without a Paddle Collection','/y8VxZEETD1N7dYkLZ5iNRcUjL44.jpg','/atR4dzV6GYogbtOTuSCiq3cWN97.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('James Bond Collection','/HORpg5CSkmeQlAolx3bKMrKgfi.jpg','/dOSECZImeyZldoq0ObieBE0lwie.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Omen Collection','/5De8Hqq0z9gmDM7SbWU0C5pTjPC.jpg','/97vU4Y2bBmoJ3Mwi3uOAL8ahdUC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Sheriff and the Satellite Kid Collection','/xy7NZTjhc2ekfP2oSn9AR6vTNmQ.jpg','/isksgMiFiRG36nqvShoVOyQzGa3.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Django Collection','/jvzJLNcftgLV40upfMozhJRKdvl.jpg','/kzM0t0wok7gMsRPTxS8a0JuTcGW.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Infernal Affairs Collection','/3D2jatriBWHO5NcMFwG0FYfmdbB.jpg','/ieW4mJg2C3HYBWSUM8lElbf9s6D.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Texas Chainsaw (Reboot) Collection','/XOaVIesSBaEXxzu3Slf80jaZwN.jpg','/9z2HzirMPY51IBrBTFlt21JX3iP.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Invisible Man Collection','/fK4kwiFZ7fGzYMkUa826KGSPriF.jpg','/k5xCUEzPzNkiMmd7gkIGCo4VB8W.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Showgirls Collection','/6Doq6SInhJPEeXXWhsbjrAgsgez.jpg','/nKMLBnDGCPdHipJs0Xk8NzNmLFS.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Saturday Night Fever Collection','/qWXxKpBdnMlQyP8f2WPIE3iCL63.jpg','/A2AJq3nwo4UYN5edFQFqI7wnjHC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dr. Dolittle Collection','/yGF6vv7ekbkf9C3FRjrGIrkyyhc.jpg','/dtz0ju3dikZaiSJ9HmVoMs9imT8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Children of the Corn Collection','/v6auJblMcNxUmZx23mQXMHmzyY3.jpg','/g4aK8Up5zSegesJdMYbxDcndn20.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Candyman Collection','/ty8ibfM6ei1tFjyvFCllMjzUxet.jpg','/hJjCx4njVdHJobhvr84e5J6MgTw.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Tremors Collection','/dCeNEdBgkpXMIAndv02JI3DXzKj.jpg','/b9Zl30z4QfkeKhI7NPqHyCBTB8Y.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Wim Wenders'' The Road Trilogy','/dH4WJAbyApJla2fq3gjzrDdowHI.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cross of Iron Collection','/aNgXkZP4Crwj5yiDVrYDcJ72nFl.jpg','/lkEfxrhE6kAFY8l5Og5UwPquNQl.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('2001 Maniacs Collection','/31dUYbRR7tzfzgUy6koBXfmrOaU.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Naked Collection','/8cdzu60RQ9owYFbjA5tKWOaKJQi.jpg','/zGDcNvc2gN9DZDG3YFgPFGDjYD2.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Stakeout Collection','/arVMKLlXLFcROIGB7o8KGeO0kwb.jpg','/w8iUdmVdeOIc1AAOJLAu8hEl7g3.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Atlantis Collection','/8Dx5iuGhol3eqVUzLK9CQEWj7G4.jpg','/vJOfi2m9yaQGu7LPRcBL44KDU7r.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Joy Ride Collection','/ln6CZn4pEBOea3757FaMukhgp25.jpg','/eDU0xWJge0Sj2A1hyp5NtTcc3OZ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Herbie Collection','/fD9IHehwlfRjZSUShCTcamxdfAP.jpg','/hgi9EeU50KFhv9pCDmJyx4VLp5G.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Pet Sematary Collection','/iySOPKFg4DgtjY9ySsJZoccMcIB.jpg','/vK18Xz065I4BvRB8r9IrH98ebVp.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Navarone Collection','/thS5HHqTi2sFq2Qfk22LhGufHkg.jpg','/quXPBggya3DoHnxZZ6urOR9e6vR.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Nobody Collection','/nGhbOT8sSe3cbfVRgfrXA7BAtbJ.jpg','/1NsrPg4Hv8mDjk60Z9ehbmgxbPC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Babylon 5 Collection','/4SmQl6eoFuyvHPj1noqqKf93yK6.jpg','/mpiKaJZSIDVGbuKxL1KyQPxeW6Y.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Agent Cody Banks Collection','/rWMPgI0adzrSAU8tJJWGQ4ABDpm.jpg','/gh0OZpG16E5LtTAkCRkr5j0v1Fh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Return of the Living Dead Collection','/7ekXvck6C94gKbfH6WlKK2qqdVL.jpg','/sgOyuSHKowya0OJprukWUpXsZGq.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Tall Blond Man Collection','/nvikKNcoe8WeFE5U5Qgi6lVygmw.jpg','/ttjbXNCNz7Bm9YdLVhXGXBJdy4j.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('High School Musical Collection','/dXIgM9sEWIkUfRH8GZUKHv1t5n.jpg','/t1mwGPJi3NkwMeyeUHr9zlQhlTo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Fox and the Hound Collection','/ph2KiQxp8xmgA5ENoBhETvJnYw9.jpg','/qwbhC5yqTYqbmhfvOEgSRmqDeSK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mr. Ripley Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Joe Dirt Collection','/oweH0mRKoguOQTKfJqNtAEwVx8Z.jpg','/x1blCWyMyhAfZ5nDmqUHtdyATFS.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Creature From The Black Lagoon Collection','/f41TORvnRk8u9nZ834uxAzxIGuH.jpg','/jPVq82CMKAm6fKVeW2nyRC2X9Yc.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Armour of God Collection','/1iBNYhBb0k0kJgIQiUbW0iOuorA.jpg','/rXGl1WJINCV2yFOikNBqYvdyeAn.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Die Lümmel von der ersten Bank','/dqhQ6N2ptjmPF1JyNe9WsA3iG7Z.jpg','/pWyiWLDtq4HHWlV4bKkUHXgTYxr.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Ratten - Collection','/razt5fQfarCK8vIHWgbmWV2huPI.jpg','/oqnZxZivDtR1vy5dCqUp0biDEaD.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hoodwinked! Collection','/bOOwzWIPKb2CkEgQXYaCvjvZJOm.jpg','/sIn465LgZqpxWnNjXSmpygpRnl3.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cats & Dogs','/sNNxLRtwl7ofzcrFFROPSlYPKxM.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Smokey and the Bandit Collection','/XYTaoh3qo6gYvJ8UAtnY9icY2Z.jpg','/ldGGb98U7ytidfLHY5wKazeB6MO.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cheaper by the Dozen Collection','/A1R0tVtO3mdaouBj6qnREfmIhtI.jpg','/abIbeEqOhnEEeEOjalyI16KlAbU.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Richie Rich Collection','/auvU4jknHdc2QVylHhZ22e2vYBD.jpg','/bglOxBHkF8sa6mmeKLue9llZ0d8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Scooby-Doo Collection','/YAuhbJKSG1R42QHJmbGsNQ80Fd.jpg','/aj598PG0VipBkiQXtikXdX5jRR4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Exorcist Collection','/yBsDTPyTboFFZES4TV7quBYPoqO.jpg','/gZnEheMdhKxSZQUEzphCHXldud1.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dei Mudder sei Gesicht Filmreihe',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Iron Eagle Collection','/wr2LChB1p1U8qX0rF2LdQgMgtAJ.jpg','/jgfkfXcsRLLmysrHFuINadUwSKV.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Asterix and Obelix (Animation) Collection','/mJ85mdtrQl2LWTNAHHcSJC55dcs.jpg','/vJH09M0PoZVdeMGnNzaeFAcsQV8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Flatfoot Collection','/aFYZwT3ja12fxFCIRH7yYyxtfdO.jpg','/ea8ZuMrCfHMYiW5efInFYEmPOUS.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Terms of Endearment Collection','/cSxkhlwKAHfJdsHTryYhTCvXl10.jpg','/5OjBecfq9Se5tKElwrDWwIpfFE6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('遊☆戯☆王シリーズ','/zEHnYMSayT2TkWKQkvR6ObAH7Hx.jpg','/vey3MFgpJD040FBOy8iXAda7F2l.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Sophie Scholl Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('House of the Dead Collection','/jZiLJV1yUez60J361t8fN2zDMEu.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Major League Collection','/u4XZNh1jdUsetzQ9XjUQGMgIsdM.jpg','/vNqeD5ECuhb7FdQiOPCjeI23YK2.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Problem Child Collection','/aIWRqX5mJ9RPKox8sguNutPCiX8.jpg','/3qrIGlVQTi7Aps9IUm9vAep9C2W.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Fortress Collection','/uJSC49XQfyEhX34nJyK07vj9RLx.jpg','/9SvdFEU1aCfC8AFmEHvyHN7fT9a.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Princess Diaries Collection','/3uDvh88xbVpRKMBw5JD0gbptvPJ.jpg','/zSEtYD77pKRJlUPx34BJgUG9v1c.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Rescuers Collection','/27YQ0qV5AolUQ4eX5caP0VbNLdQ.jpg','/bR0XKmrmPZtHX6oQ1nH1DEPX08G.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Prince & Me Collection','/gw6Mu3cfjNEQ5IUeNpqs7z8CIOE.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('National Lampoon''s Vacation Collection','/zvEUkLpDO7xlgabBEA9CCc0cvAt.jpg','/pBmhj6KkEjlzc3e7jAPkIHgGIrE.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Honey, I Shrunk the Kids Collection','/xxIwqQARS0RZu5cIENahqZSRw2a.jpg','/sfT3NqSnjEDY1449qBgQRWOIcaq.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Elling Collection','/1iGTBg6M2ovwQhoxyeREW1uNV3l.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Go Trabi Go Collection','/6IHS4745u85kTFhytq1Hx1tErAc.jpg','/f1BA3oOPCJngP3MGyT6YKCmC9VI.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lucky Luke (Terence Hill) Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('My Sassy Girl Collection','/wSINESGEqXGxRaRgalJACcANapm.jpg','/rngutP2LYdj8Hizn3Ufmh5mBZ1C.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Girl''s on Top Collection','/aCmjvFfEMXDxP2dSCTRORXrmg2H.jpg','/ysyPMmhgZ9Z4heU7vdUBP7L5zCl.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('French Fried Vacation','/ncWcoUxQIn7wp3d1idOxQ7wM7R.jpg','/hjk94JWHQcYEWftJAssFsNhSr9L.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Patton Collection','/35BSF0o2YD2nHn4okEVGX8oRVNa.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Bring It On Collection','/iybFuFGBKPD8LXOgugjnA8sI6Bb.jpg','/ypR7RZO9hIAyd3lIx07gJ0AVvbB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cinderella Collection','/ouN0BQzHKOqK03d9qKXP7JOgQdt.jpg','/yNq1UsclAyXaQGhXVSDoyS9wpFo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Freeway Collection','/u5BhFwbnLg07R9VXlPeSxKT0FNR.jpg','/ysDeNGwgvTmdYuBF7njZ71bVIh4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Drunken Master Collection','/4YKqOyFW1IP4jyX1vy5BooM0dU.jpg','/3JWhJ6h9iR3ugJWxo7lcJl5L5ii.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Secret Garden Collection','/zy16gzORcFshGK3oE9W6dhQ8yRZ.jpg','/tpNVr5BikRH4tkNJPbYM6Q9yD1a.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Anaconda Collection','/sENQAlXOhOb2QmfpFl2w34W9ODP.jpg','/uR7j2TEwJVCMz7CDJgNPuhty4J9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Aladdin Collection','/enl57YvMhTAdic6El5rfZppyzq2.jpg','/naeLgo2bt4WKfHF4BTrG6mkmjiY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Care Bears Collection','/zsZ9BkSg0ce9PDcRIGTVFdxMiZs.jpg','/lcXu4fxsrLZOzuwUXYKdHtlauBP.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hellraiser Collection','/lIK0UgJsA18Z5I1PwpucXzgyF3A.jpg','/uaEUgCqB6lGkvM4Wy5blNwLJdfa.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cinderella Story Collection','/65raP1FRJpPC5GVWVvemQ3kLAKG.jpg','/iVqkNuy2jpcurdk2ZH2iAexJTo6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hellboy Collection','/81B1OdGY7f3TVN06eKra25vHzYk.jpg','/o8HE9b55OKCwGLpQB4LMHGbpNgi.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Crazy Race Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Harold & Kumar Collection','/f06PD56BU2MFNOysMAxdvL80aEo.jpg','/b70mFgsSn2hl3CvC0nRx0SHUEX0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Nanny McPhee Collection','/iM75l6CCjaMOLUAIyAEfv6ISyQJ.jpg','/8Ndh4t4DKrsyhasy0ZZ30raEoD6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cannonball Run Collection','/8Bq9YD1UIw1hdkccegKVaUipBH9.jpg','/qVJfEqe9FvzrzjMzftohcQwRvsf.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Howling Collection','/g04UfThJDQSx0rQlEgNsjThCsjy.jpg','/a0UuiTYxqMmj5Ll26rORaFoTKBc.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('City Slickers Collection','/1xHwbqIfBQvxNCkdJwQ5vxFwI5H.jpg','/qv2Bcy963o42k65v0km97G1ceZ4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Qatsi Collection','/AlE6QJc87zH5vYw6AI779ywRZG6.jpg','/2pRLc3z0jE1WkFJLCZyITtYjo08.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Dead or Alive Collection','/pkZCiGxwgFPlVwu5TOdo6KQLhVT.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('My Girl Collection','/stM5jbbap6O9qxOZ2p9qDfk5AJH.jpg','/zdeW9SAF9MGMSnxlwUheQOyL80K.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Pusher Collection','/9pM6Rr8WsVqAzTxYswPTNoICNno.jpg','/aNQuRUYTz8CT9HxlNLj4oJ9ctut.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Warlock Collection','/oujdAIytXUwEHQY589ZGvrIpgOF.jpg','/oMHsUu1CPf8h9BLg7qSm7oPuFjS.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Jeepers Creepers Collection','/2qyn3GJXqLP54fbWazRGvsnkmAA.jpg','/mzFtvzOdmuDYoQQuOzulsJkAUQB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Odd Couple Collection','/iSRzUpJBro5vgskqVlCNOvXNxjh.jpg','/kY2nJgcvBgjLuAJxygbXYv1el2h.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Walking Tall (Reboot) Collection','/mtMPcKsMLutz4pR6N65tYEs4ali.jpg','/zzVAOPbmA8bGmRVV8NsV8swBrbG.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Mexico Trilogy Collection','/qmPhILSFQKaRyc81mVJWl05tHai.jpg','/6p1OzuIKWnTDfDea7IpB9xra5J.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Superman Collection','/AaSF0IxlWb959ZHFN20oDpZ9GJr.jpg','/la0EhOrgVAiY8sf3ILz3wgoaNXH.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Begotten Collection','/eTmRdQWGkVbxO5YXvkvSf3BFbQ.jpg','/fKj5F5U26FVKx6Q3Wyd1XxVpu3r.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Teenage Mutant Ninja Turtles Collection','/hxcTQ9aR9U2hOWyy7S1HoBDFprA.jpg','/7dusELv6x1ANRGorNvqbKhKIUPY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lost Boys Collection','/rpuL8zSLmVt34gwk03gSGReSjog.jpg','/qXpWa7kDopkOyEhuZtOLgIh4SW9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Klapisch Trilogy','/woD0gFHbZgwi9RpLL0uSQ56hnJA.jpg','/p7g6oUYWhKS1TmLo4xBMnDNcsGh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('28 Days/Weeks Later Collection','/4AeGz1Jwnq6ky2kfLT95Tm8nEiw.jpg','/oLT5tHDNzb5LfytO2g7q6dF0QkC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Die Hard Collection','/xhnb5lVfwE7NHycdPNdIxHx7kZi.jpg','/5kHVblr87FUScuab1PVSsK692IL.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Resident Evil Collection','/ed8cYt6V7DVoVuHhBV5dD2YRFvb.jpg','/8utTJ9WoQeYcZ0Ztciv6auqwLXl.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lammbock Collection','/kEasQuxb1LYV7sOaaGl2NQ0iMLJ.jpg','/9BtQ6KC6QIT824WZaeMf5JZnXKB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Night at the Museum Collection','/q2nwE0Qi8U6tsU5HDmiWS2D3dSJ.jpg','/z0nqqHwEY3niKa41kKbR4zhnvHw.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Pink Panther (Original) Collection','/xu6gZ0zGUSR8SC2QLKFaUrX2niM.jpg','/9Lc4YOIwprqMYNaUkJRRa5unakk.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Meet the Parents Collection','/WFkinadVm4NRynRKuUcaLFNIDx.jpg','/7UWRq79VHc58QXTSn57UsOUKQLZ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Erkan & Stefan Collection','/CG2JugGacOCWNK3oC7AtZDn2Il.jpg','/6T80Y17D3uRyDkX74wjUns70Yfz.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hitman Collection','/brAGl1VgP5tApySlUymCza1nMDA.jpg','/mAOyrGwmHUdIkCy98JGvuEvZQCk.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Free Willy Collection','/3M2Q9ZDTyFBfi3ohz2gizFmnoL0.jpg','/aef15QAJ8Kxbh8W5zXqJb1f9Vhw.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Speed Collection','/nK6q8iJYl39vVq8vmwR78CUDQp0.jpg','/5YDT5pRGMvuOqOk7SWBq8HBrbGm.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Net Collection','/sO76zaomJunfbwKmoeDvPepgk6P.jpg','/5j4HxayNgcAgGStNKqPxM0QNC7V.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Bill & Ted''s Most Excellent Collection','/ffCa2h3qW55YthUbz6gsGnkaCes.jpg','/22AGOxmG9DAC1gUbLWnA0OcNbqh.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('00 Schneider Filmreihe','/20Ik4axObKdCQOhHE2Hj8E9f7oK.jpg','/mqmNfqecVb6M3hu3miKb3nUHYlZ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Dirty Dozen Collection','/xCLD1Pul4d6iJJdFf3el7PfMpLc.jpg','/z5Wj3wkksrRjyjhZ2flr00gSjTR.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Zorro Collection','/hy8YFvaURGzKFoBbB8ajjzlWQne.jpg','/wZCWCe4jPJz04dvVGLQ8TtOq9Js.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Gus Van Sant''s Death Trilogy',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('March of the Penguins Collection','/wloYL425S9UBjwE6NF8fH4nvtML.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Jack Ryan Collection','/skZcEtS90hiSD08P0tw2YY87j3i.jpg','/qYlcVBifq5T4wyWV00a5Awq0kUi.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Godzilla (Showa) Collection','/scvwS6k8gIW8w24UcmePQqVL10l.jpg','/dx9YSup5zEOjxYwG4UkYBVAZIXo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Planet of the Apes Original Collection','/7OvC0TNbINmhfEmi3lMYEnGWNOr.jpg','/eYf3GRnuVCgeFQfEo0qK7ua5rCR.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hostel Collection','/2jLQFRlH8CC9cptcANY5cEtC1q8.jpg','/rXf4gEh8m3ZcK9KHkxT78Kscxee.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Re-Animator Collection','/j1v4JQUVwCDH2KKJGjFeShXp2JT.jpg','/hbrbyH7H32veX4bDWjunpVQ9UNT.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('House of 1000 Corpses Collection','/rNLKZ2sgHuLoxV63wEaWAwCrsLN.jpg','/osLewbX6FJMy1iUcNHm6hoiNH0j.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Anatomy Collection','/aTwYyzXQJVrUt50hReNJ8nvOYgo.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Mummy Collection','/4UMn5KmXopgpkC862Ms3t5j1sXl.jpg','/1BeKi6IytbfQlQocJSvP2k6sO1a.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Captain America Collection','/2tOgiY533JSFp7OrVlkeRJvsZpI.jpg','/ezEpSQhUQxVKdMx81zaSLsTHv7j.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('An Inconvenient Truth Collection','/m75rGUMXzUCehxfcPjIdE8IPRlT.jpg','/i6aMNdpjDpnMnJLJ8L0KFrWdJdT.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Angel Collection','/q52KwBiFKkXKqVKb8t2Ob68mBxS.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Teenage Apocalypse Trilogy','/8qqgNGdetjo5l9PLD5iK5iRisSd.jpg','/3pzDZR85GPgdC6b4HwHqzqeEDfB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Philip Marlowe (Robert Mitchum) Collection','/q9qCtF2bh9NosMAIxcMNWyd1eo0.jpg','/vxpXR16tCm8i10pfGUl1qWJ14Fe.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('2 Days In... Collection','/qa9forb9tyQsyyQbXeMBtgpURCc.jpg','/gzj0bdcB3zZ6u5JSfFBd2TRCcAz.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Transformers Collection','/giURBCO3r4LVbhywEjIuYz92fEv.jpg','/zvZBNNDWd5LcsIBpDhJyCB2MDT7.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Pirates of the Caribbean Collection','/zRBaZxS5YauLvRYjAdL4AUCwlht.jpg','/zJd4E0ImT1U6O8k6aX3ssc9iUBS.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Fantomas Collection','/xxE1cXieDAUa8XtarhS9JCCyvBt.jpg','/3WpCsnVPmlvVVTeMxDTQT4XGtog.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Star Wars Collection','/r8Ph5MYXL04Qzu4QBbq2KjqwtkQ.jpg','/d8duYyyC9J5T825Hg7grmaabfxQ.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Amazing Spider-Man Collection','/68CqVxCH14br7EHFu67peDDjZX9.jpg','/aLrNTcLN2kDu9jAJ4tS5haiWGc6.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Stomp the Yard Collection','/2qAqDHlxVS4wOf1Z8mBGpTgp7PB.jpg','/zuaYuIAgnCY7Y6nkSGGhPx8RlOV.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Crank Collection','/wmUzRqcAi0KOW7sqnaAvEQtM8l.jpg','/cziWkSXQG3Vul0l3Mu2sOXLS1dC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('USA: Land of Opportunities Collection','/3uOD2TspgF0CbHu8g5SGzJe0YQC.jpg','/qMA0dQpuhOb8UtAaEj5PasG3mCB.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Butterfly Effect Collection','/4K2RPVSmHiUBD2sAdVJS3E0h7dC.jpg','/mTmug8FHz5BBnYfmkJNzcsJ883V.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Grudge Collection','/dohOSIYDEK42stdfKo0pQfrve0h.jpg','/nRfDTqIuaVLu2aB0qFuSmw8btp0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Fantastic Four Collection','/prObnUSCHIBC8ZjkGo2KHgjkWOo.jpg','/3JFe9AWoKuQWox7HO8HKgYRMOF7.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Tomb Raider Collection','/sgaP4WtVlKzz8FIcjbkevOycJiq.jpg','/aJQsaYuDvawCyXgjq8JepPI4tz.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Sister Act Collection','/m9xbNgB8MrrGOCvc4vjOtSWdqh9.jpg','/5zLMzYgpx2TNmISTk1MnRyRWY9M.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Hard Target Collection','/g7Bc4ik16xOBz21BQOcsxrBL8BO.jpg','/wcBIwQY888HX1QWpnv43lAujoId.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Tanguy - Saga','/j902bNYza6qKUXwLeuDkIKtdwdD.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Alex Cross Collection','/udn1n9NrzaotFHDk6hO3onMmXcB.jpg','/eyKpawn8yMq6kdv03wgKruMuSJX.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('National Treasure Collection','/z5EIRaI8XS0brelYwDFEVlxcpzM.jpg','/a0GLVfaDSf5GNZKK5H4FgGCD2VW.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Whole Nine/Ten Yards Collection','/m6tkyCcOm4wzklAvsT0jyaM5mgY.jpg','/ttaiuuOHjYLTszcbADBZImqRK5H.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Chaplin''s Mutual Comedies','/A6OcUvDaB20YIUfYe2UcCM8FE90.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Wolverine Collection','/c18HVnKTybcAUYVQd8rOcdbqwY.jpg','/QtSxEuCwcZSfCTMZfER3nHDVsG.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Halloween (Rob Zombie Series) Collection','/eFfRMP387MTJ4jl0gcE5jvS9XXN.jpg','/tXXPOkcFLcDiJ4OU5SOU3JnhQrg.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('American Pie Collection','/wpN87k1PGhpdd5c2FQkaUpZYJix.jpg','/3ptXtaqzAZlMXn3nZxaYke4anmK.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Rush Hour Collection','/pTjvzlYByJuZ4TTkmlHIe4aDFy2.jpg','/uoDt3eCCKpcxSQVWjPTgN8T0gjm.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Storm Riders Collection','/91OBePxelvhb29PEIXflME5opGp.jpg','/zhp6Z7FfiXEyAHMltTaw4rTn4TV.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cleopatra Jones Collection','/1b6HdffTfb8hCnm1A9zQggetHBe.jpg','/unXiJ372Cq9W6ZhOMqsR0Al5Zw4.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Stargate Collection','/dxlCi4530gCAah2QlW6nIGUH66d.jpg','/fwVVh9o0WZsZNstpX3O55ff7Hs8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Glass House Collection','/5cClctuwqZYg4txbHrtLKHCXQSU.jpg','/6vjzBXBgaDkMjhEzQ8xjGAkpaow.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Killer Tomatoes! Collection','/6Q7wXuL3xJkSlVuIPDrkMDkuuy8.jpg','/bZjdeLSATekfG0ctw2WlYQgUDDt.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Heimat-Trilogie','/a3NDsarTyXm3BKvGxR1WuRFJ2HW.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Cities of Love Collection','/xuS31uodmwHNbB6dfKUezOYQNI3.jpg','/hPln7ZijNOnPtCoEsER2MnLvBc9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('World of Watches Collection','/5k6kkMpPCDqelJ2X1RABHCbstE6.jpg','/ubshur0qNQdZskqKx8l8n7lmJ4o.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Clerks Collection','/qEjGvJ9I2ak6ENjdJ23dfjqLkAK.jpg','/6Fjkbh2DVAvVZa3c1HamblAN5Bg.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('In the Name of the King Collection','/sGZ0KQnLLjtneVhH9Z8tU3I1mdZ.jpg','/rJaHFKkYvtnjjJ58L9W5KgYxA6w.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Taxi Collection','/nCzy28TbMJDJLxuaPgQZrLgmuT7.jpg','/74R8bq4RDuxK3F0VPGlse4YH3Ab.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Asterix & Obelix Collection','/f6C6tDEU3aJndJokSLvYLuwVt0k.jpg','/vm0i4KIscrTiUsri21z1SOIG4fo.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Les Amours sous la Révolution',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Sherlock Holmes (Basil Rathbone) Collection','/lpwityD1aZbWtNB2rvYb08TMMvG.jpg','/e5NsMo56xOYqt1EwOvy5GYlGrLx.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Un éléphant ça trompe énormément','/68zFIZT8xzN4b2LoICzrwjaArEb.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Running Out Of Time Collection','/5bQraniOdRa6qLcC07Gi2CwngbA.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Lady Snowblood Collection','/d7ztUEeUpp3mGrD5xoLpi4sH8ad.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Bourne Collection','/5wcNRGQ5oexJlJUkHyIFT5org4Z.jpg','/vA5xMglyZv7yzDTj1qUTU4OvelV.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Short Circuit Collection','/gU0WgYpbWfiZfZFnBvRrI51Pa0U.jpg','/o3C0qlKyg7Haot9ZVqtRtsrKwWc.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Splash Collection','/tI0RB8ezHm7NMRuLfWIh4mWuGXY.jpg','/9uSHQAAUYFt6WSL2sz9zgvnXnvk.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Aces Go Places Collection','/63vfOuKjRtGngcddEoZHzpqmKRK.jpg','/d7DAqeTxESYrBQrZwAD4gx5K8yT.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Airplane Collection','/u8IXYbpoRcKMlnhUvND0NB8HsAM.jpg','/w7bNIqVMZaaWf1LnMIZ1HywXbP8.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Blair Witch Collection','/qDQuKJZYLHrs1Ej64tYYFooFxc1.jpg','/e5GwLq0zBer3SuSJZodcNROnT6Z.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Ringu Collection','/eQX9SK5WPdsKWRGLfga4w9KuskV.jpg','/aS42DTtR6UYNLfKdKJBKYL1OS1U.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Almighty Collection','/v8fLc8oQxLJw4pYrE0arjLQiwhl.jpg','/qKuR7BpBLTcISNWgxKQmXnYYJFX.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Sides of the Bed','/vEFselfDCfcx0NMUcHMI6nJlZo6.jpg','/nTTRmNXdKxlZYEbjjgbpSUcGIDX.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Addams Family Collection','/2ZVopkpVBRkgY1G3iMWFmoo8TIa.jpg','/gS5yZLrSJ6uNbsz17xoxf70X2Ws.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('All Stars Collection','/823g88J58s4bnhKT4ADXgOFFt62.jpg','/g8XTODghMizLlEd9TJ9NsRXaYh0.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Chronicles of Riddick Collection','/4R2zrqk9KzgxU9UDH3yUUsENXR.jpg','/xb5zyHecWA7UACdiNPXDA3m5HSY.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('6 contes moraux','/hI8apMVXtSOlvUUryGYiFG1sQOd.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Backdraft Collection','/pYjrDzhYgflAG96nLtBHhSr97IE.jpg','/xODyLuXCARWbEj5Allf8F3b5ZfH.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Musketeers Collection','/e4sHW14q8LnfJG4rjyXotJHA9KM.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Homunculus',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Ghostbusters Collection','/sctvCtE1M1rDF4f0W2fMrk2BrGB.jpg','/9vlVnAJv5zidg0fyTcV0ljIzyl9.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Lost World Collection',NULL,NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Frankenstein (Universal) Collection','/2PJYpPHOqnVMXelHV1T4t6zra4i.jpg','/aP0pbkGzEpBhCYnZDf72LLS2sU5.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Ace Ventura Collection','/guYqF6CvU48aGH5nTx160Bjg35F.jpg','/aPoX8RAxA9J2XW44Ud0AozTUFop.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Matt Helm Collection','/kZYAYSsMfJ0UTGEckdLxLnaXhnW.jpg','/lzBvyOWVm6pj608QZUlcHLid0FN.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Frankenstein (Hammer) Collection','/p0KHQiCZCYjjksOVjyseO9BByFT.jpg','/gl9Gi60C9WYVkObOMll19OROhMC.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('The Wolf Man Collection','/bYvHmIKqSnUYyjFhabzNliS2qu1.jpg','/8DcHcYH0P9de2j8HPRYq9wXNaIf.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Basic Instinct Collection','/hiM5EvFgjFboZtPMY5vFjhNnRQc.jpg','/o5rgryRLwlOApsO3toqpqhhdS7H.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Tulse Luper','/eqSFtrfNg870qOpmPkiPKO9w8SD.jpg',NULL);
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Frankenstein (Toho) Collection','/vg1YnFLhw1FAxZiZaVlhY7BcExD.jpg','/7qTWrJPPyrsnGz1jJaE4HZLKhmd.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Bambi Collection','/b941y7oiWBXJZaoWemW4exlpDxf.jpg','/pdeV9HC6ECDvUfICMWeMHvWsCIa.jpg');
INSERT INTO collection(name,poster_path,backdrop_path) VALUES ('Battle Royale Collection','/cqfdgRMmuCMQnc7e600EGnSsXx.jpg','/gKpdj5aKtxrAoAbJJ3EtBZHcsyP.jpg');
