INSERT INTO country(country_name,iso_3166_1) VALUES ('Colombia','CO');
INSERT INTO country(country_name,iso_3166_1) VALUES ('France','FR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Italy','IT');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Australia','AU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('United Kingdom','GB');
INSERT INTO country(country_name,iso_3166_1) VALUES ('United States of America','US');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Germany','DE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Canada','CA');
INSERT INTO country(country_name,iso_3166_1) VALUES ('South Korea','KR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Hong Kong','HK');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Mexico','MX');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Czech Republic','CZ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Romania','RO');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Austria','AT');
INSERT INTO country(country_name,iso_3166_1) VALUES ('South Africa','ZA');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Switzerland','CH');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Belgium','BE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Ireland','IE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Japan','JP');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Norway','NO');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Croatia','HR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Thailand','TH');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Greece','GR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('New Zealand','NZ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Denmark','DK');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Netherlands','NL');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Russia','RU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Soviet Union','SU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Sweden','SE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Hungary','HU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('China','CN');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Morocco','MA');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Argentina','AR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Spain','ES');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Portugal','PT');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Luxembourg','LU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Singapore','SG');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Taiwan','TW');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Brazil','BR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Tajikistan','TJ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Uzbekistan','UZ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Israel','IL');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Yugoslavia','YU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Finland','FI');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Poland','PL');
INSERT INTO country(country_name,iso_3166_1) VALUES ('India','IN');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Bulgaria','BG');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Chile','CL');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Turkey','TR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Lebanon','LB');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Iceland','IS');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Vietnam','VN');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Venezuela','VE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Mongolia','MN');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Uganda','UG');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Peru','PE');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Liechtenstein','LI');
INSERT INTO country(country_name,iso_3166_1) VALUES ('East Germany','XG');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Bosnia and Herzegovina','BA');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Burkina Faso','BF');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Egypt','EG');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Iran','IR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Jordan','JO');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Pakistan','PK');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Cambodia','KH');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Algeria','DZ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Djibouti','DJ');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Czechoslovakia','XC');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Cuba','CU');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Slovenia','SI');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Serbia','RS');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Afghanistan','AF');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Costa Rica','CR');
INSERT INTO country(country_name,iso_3166_1) VALUES ('Puerto Rico','PR');
